query adminGetReportSettlementOrder($partnerId: String!, $periodType: PeriodTypeEnum!) {
  adminGetReportSettlementOrder(partnerId: $partnerId, periodType: $periodType) {
    histories {
      date
      revenue
    }
    totalRevenue
  }
}
