query adminGetInvoice($settlementId: String!) {
  adminGetInvoice(settlementId: $settlementId) {
    createdAt
    fileSize
    fullOriginalUrl
    fullThumbUrl
    id
    isDeleted
    mimeType
    name
    originalUrl
    ownerId
    thumbUrl
    type
    updatedAt
    videoUrl
  }
}
