query adminGetReportSummary($partnerId: String!, $periodType: PeriodTypeEnum!) {
  adminGetReportSummary(partnerId: $partnerId, periodType: $periodType) {
    totalRevenue
    totalRevenueOrder
    totalRevenueSettlement
  }
}
