query checkProductVehicleRegistrationPlateExist($id: String, $vehicleRegistrationPlate: String!) {
  checkProductVehicleRegistrationPlateExist(id: $id, vehicleRegistrationPlate: $vehicleRegistrationPlate)
}
