query myCart {
  myCart {
    createdAt
    deletedAt
    id
    items {
      cartId
      createdAt
      deletedAt
      id
      product {
        avatarId
        createdAt
        deletedAt
        descriptionImageIds
        detail
        id
        isActive
        isFavorite
        isFixedCost
        isNew
        name
        operatingNumber
        operatingUnit
        ordinalNumber
        partNumber
        partnerId
        quantity
        serialNumber
        star
        type
        unitPrice
        updatedAt
        vehicleRegistrationPlate
        vinNumber
        yearOfManufacture
      }
      productId
      quantity
      store {
        addressMoreInfo
        avatarId
        bank
        birthday
        cardNumber
        citizenId
        countProduct
        countTechnician
        createdAt
        deletedAt
        description
        email
        fullname
        hotline
        id
        isActive
        isAdmin
        isApproved
        latitude
        longitude
        mapAddress
        menus
        parentId
        phone
        star
        storeStar
        suggestionPoint
        type
        updatedAt
      }
      total
      updatedAt
    }
    total
    updatedAt
    userId
  }
}
