query partnerGetCourse($id: String!) {
  partnerGetCourse(id: $id) {
    address
    banner {
      createdAt
      fileSize
      fullOriginalUrl
      fullThumbUrl
      id
      isDeleted
      mimeType
      name
      originalUrl
      ownerId
      thumbUrl
      type
      updatedAt
      videoUrl
    }
    bannerId
    content
    createdAt
    deletedAt
    document {
      createdAt
      fileSize
      fullOriginalUrl
      fullThumbUrl
      id
      isDeleted
      mimeType
      name
      originalUrl
      ownerId
      thumbUrl
      type
      updatedAt
      videoUrl
    }
    documentId
    endDate
    enrolledCount
    enrollments {
      courseId
      createdAt
      deletedAt
      id
      partner {
        addressMoreInfo
        avatarId
        bank
        birthday
        cardNumber
        citizenId
        countProduct
        countTechnician
        createdAt
        deletedAt
        description
        email
        fullname
        hotline
        id
        isActive
        isAdmin
        isApproved
        latitude
        longitude
        mapAddress
        menus
        parentId
        phone
        star
        storeStar
        suggestionPoint
        type
        updatedAt
      }
      partnerId
      updatedAt
    }
    id
    isActive
    isEnrolled
    name
    openDate
    price
    startDate
    teacher
    teacherDescription
    updatedAt
    videoUrl
  }
}
