query partnerQuotation($quotationId: String!) {
  partnerQuotation(quotationId: $quotationId) {
    accessories {
      available
      createdAt
      deletedAt
      id
      name
      quantity
      quotationId
      unit
      unitPrice
      updatedAt
    }
    additionalFees {
      amount
      createdAt
      deletedAt
      id
      name
      quotationId
      updatedAt
    }
    booking {
      addressMoreInfo
      code
      createdAt
      deletedAt
      description
      id
      latitude
      longitude
      mapAddress
      medias {
        createdAt
        fileSize
        fullOriginalUrl
        fullThumbUrl
        id
        isDeleted
        mimeType
        name
        originalUrl
        ownerId
        thumbUrl
        type
        updatedAt
        videoUrl
      }
      partner {
        addressMoreInfo
        avatarId
        bank
        birthday
        cardNumber
        citizenId
        countProduct
        countTechnician
        createdAt
        deletedAt
        description
        email
        fullname
        hotline
        id
        isActive
        isAdmin
        isApproved
        latitude
        longitude
        mapAddress
        menus
        parentId
        phone
        star
        storeStar
        suggestionPoint
        type
        updatedAt
      }
      partnerId
      problemTexts
      problems {
        createdAt
        deletedAt
        id
        isActive
        name
        type
        updatedAt
      }
      quotationAccepted {
        bookingId
        createdAt
        deletedAt
        diagnosisFee
        diagnosisNote
        estimatedCompleteAt
        id
        operatingNumber
        operatingUnit
        rejectReasons
        repairFee
        status
        technicianId
        total
        transportFee
        updatedAt
        userId
      }
      scheduleReason
      scheduleTime
      settlementAccepted {
        bookingId
        createdAt
        deletedAt
        discount
        id
        invoiceId
        quotationId
        status
        technicianId
        total
        updatedAt
        userId
        vatTax
      }
      status
      statusDetail {
        bookingId
        createdAt
        id
        note
        partnerId
        scheduleReason
        scheduleTime
        status
        userId
      }
      technician {
        addressMoreInfo
        avatarId
        bank
        birthday
        cardNumber
        citizenId
        countProduct
        countTechnician
        createdAt
        deletedAt
        description
        email
        fullname
        hotline
        id
        isActive
        isAdmin
        isApproved
        latitude
        longitude
        mapAddress
        menus
        parentId
        phone
        star
        storeStar
        suggestionPoint
        type
        updatedAt
      }
      technicianCanReviewUser
      technicianId
      technicianReviewUser {
        assessorId
        bookingId
        comment
        createdAt
        deletedAt
        id
        orderId
        personEvaluatedId
        productId
        star
        type
        updatedAt
      }
      transportDistance
      transportDuration
      transportFee
      updatedAt
      user {
        address
        avatarId
        birthday
        certificate
        createdAt
        deletedAt
        email
        fullname
        id
        isActive
        numberBooking
        numberMaintenance
        numberOrder
        phone
        star
        totalBookings
        totalMaintenanceRequests
        totalOrders
        totalPayment
        totalSpending
        updatedAt
      }
      userCanReviewAgency
      userCanReviewTechnician
      userId
      userReviewAgency {
        assessorId
        bookingId
        comment
        createdAt
        deletedAt
        id
        orderId
        personEvaluatedId
        productId
        star
        type
        updatedAt
      }
      userReviewTechnician {
        assessorId
        bookingId
        comment
        createdAt
        deletedAt
        id
        orderId
        personEvaluatedId
        productId
        star
        type
        updatedAt
      }
      vehicle {
        addressMoreInfo
        avatarId
        createdAt
        deletedAt
        detail
        hidden
        id
        latitude
        longitude
        mapAddress
        name
        operatingNumber
        operatingUnit
        ordinalNumber
        serialNumber
        updatedAt
        userId
        vehicleRegistrationPlate
        vinNumber
        yearOfManufacture
      }
      vehicleId
    }
    bookingId
    createdAt
    deletedAt
    diagnosisFee
    diagnosisNote
    diagnostics {
      createdAt
      deletedAt
      description
      diagnosticCode
      expense
      id
      quotationId
      quotationPriceListId
      updatedAt
      workingHour
    }
    estimatedCompleteAt
    id
    operatingNumber
    operatingUnit
    reasons {
      createdAt
      deletedAt
      id
      isActive
      name
      type
      updatedAt
    }
    rejectReasons
    repairFee
    status
    technician {
      addressMoreInfo
      avatar {
        createdAt
        fileSize
        fullOriginalUrl
        fullThumbUrl
        id
        isDeleted
        mimeType
        name
        originalUrl
        ownerId
        thumbUrl
        type
        updatedAt
        videoUrl
      }
      avatarId
      bank
      birthday
      cardNumber
      citizenId
      countProduct
      countTechnician
      createdAt
      deletedAt
      description
      education {
        createdAt
        deletedAt
        id
        isActive
        name
        type
        updatedAt
      }
      email
      expenseInfo {
        cost
        distance
        time
      }
      fullname
      hotline
      id
      isActive
      isAdmin
      isApproved
      latitude
      level {
        createdAt
        deletedAt
        id
        isActive
        name
        type
        updatedAt
      }
      longitude
      mapAddress
      menus
      parentId
      parentInfo {
        addressMoreInfo
        avatarId
        bank
        birthday
        cardNumber
        citizenId
        countProduct
        countTechnician
        createdAt
        deletedAt
        description
        email
        fullname
        hotline
        id
        isActive
        isAdmin
        isApproved
        latitude
        longitude
        mapAddress
        menus
        parentId
        phone
        star
        storeStar
        suggestionPoint
        type
        updatedAt
      }
      phone
      qualifications {
        createdAt
        deletedAt
        id
        isActive
        name
        type
        updatedAt
      }
      reviewSummary {
        percent
        starAverage
        total
      }
      star
      starInfo {
        star
        total
      }
      storeReviewSummary {
        percent
        starAverage
        total
      }
      storeStar
      storeStarInfo {
        star
        total
      }
      suggestionPoint
      type
      updatedAt
    }
    technicianId
    total
    transportFee
    updatedAt
    user {
      address
      avatar {
        createdAt
        fileSize
        fullOriginalUrl
        fullThumbUrl
        id
        isDeleted
        mimeType
        name
        originalUrl
        ownerId
        thumbUrl
        type
        updatedAt
        videoUrl
      }
      avatarId
      birthday
      certificate
      createdAt
      deletedAt
      email
      fullname
      id
      isActive
      numberBooking
      numberMaintenance
      numberOrder
      phone
      star
      totalBookings
      totalMaintenanceRequests
      totalOrders
      totalPayment
      totalSpending
      updatedAt
      userAddress {
        addressDetail
        addressName
        contactName
        contactPhone
        createdAt
        deletedAt
        id
        isDefault
        latitude
        longitude
        mapAddress
        updatedAt
        userId
      }
    }
    userId
  }
}
