query partnerGetDiscountCode($id: String!) {
  partnerGetDiscountCode(id: $id) {
    admin {
      address
      addressMoreInfo
      avatar {
        createdAt
        fileSize
        fullOriginalUrl
        fullThumbUrl
        id
        isDeleted
        mimeType
        name
        originalUrl
        ownerId
        thumbUrl
        type
        updatedAt
        videoUrl
      }
      avatarId
      birthday
      createdAt
      deletedAt
      email
      fullname
      id
      isActive
      type
      updatedAt
    }
    adminId
    createdAt
    deletedAt
    endDate
    id
    isActive
    isAssignAllProduct
    limit
    limitPerAccount
    minOrderValue
    name
    partner {
      addressMoreInfo
      avatar {
        createdAt
        fileSize
        fullOriginalUrl
        fullThumbUrl
        id
        isDeleted
        mimeType
        name
        originalUrl
        ownerId
        thumbUrl
        type
        updatedAt
        videoUrl
      }
      avatarId
      bank
      birthday
      cardNumber
      citizenId
      countProduct
      countTechnician
      createdAt
      deletedAt
      description
      education {
        createdAt
        deletedAt
        id
        isActive
        name
        type
        updatedAt
      }
      email
      expenseInfo {
        cost
        distance
        time
      }
      fullname
      hotline
      id
      isActive
      isAdmin
      isApproved
      latitude
      level {
        createdAt
        deletedAt
        id
        isActive
        name
        type
        updatedAt
      }
      longitude
      mapAddress
      menus
      parentId
      parentInfo {
        addressMoreInfo
        avatarId
        bank
        birthday
        cardNumber
        citizenId
        countProduct
        countTechnician
        createdAt
        deletedAt
        description
        email
        fullname
        hotline
        id
        isActive
        isAdmin
        isApproved
        latitude
        longitude
        mapAddress
        menus
        parentId
        phone
        star
        storeStar
        suggestionPoint
        type
        updatedAt
      }
      phone
      qualifications {
        createdAt
        deletedAt
        id
        isActive
        name
        type
        updatedAt
      }
      reviewSummary {
        percent
        starAverage
        total
      }
      star
      starInfo {
        star
        total
      }
      storeReviewSummary {
        percent
        starAverage
        total
      }
      storeStar
      storeStarInfo {
        star
        total
      }
      suggestionPoint
      type
      updatedAt
    }
    partnerId
    products {
      avatar {
        createdAt
        fileSize
        fullOriginalUrl
        fullThumbUrl
        id
        isDeleted
        mimeType
        name
        originalUrl
        ownerId
        thumbUrl
        type
        updatedAt
        videoUrl
      }
      avatarId
      createdAt
      deletedAt
      descriptionImageIds
      descriptionImages {
        createdAt
        fileSize
        fullOriginalUrl
        fullThumbUrl
        id
        isDeleted
        mimeType
        name
        originalUrl
        ownerId
        thumbUrl
        type
        updatedAt
        videoUrl
      }
      detail
      id
      isActive
      isFavorite
      isFixedCost
      isNew
      manufacturer {
        createdAt
        deletedAt
        id
        isActive
        name
        type
        updatedAt
      }
      model {
        createdAt
        deletedAt
        id
        isActive
        name
        type
        updatedAt
      }
      name
      operatingNumber
      operatingUnit
      ordinalNumber
      origin {
        createdAt
        deletedAt
        id
        isActive
        name
        type
        updatedAt
      }
      partNumber
      partOfProduct {
        createdAt
        deletedAt
        id
        isActive
        name
        type
        updatedAt
      }
      partner {
        addressMoreInfo
        avatarId
        bank
        birthday
        cardNumber
        citizenId
        countProduct
        countTechnician
        createdAt
        deletedAt
        description
        email
        fullname
        hotline
        id
        isActive
        isAdmin
        isApproved
        latitude
        longitude
        mapAddress
        menus
        parentId
        phone
        star
        storeStar
        suggestionPoint
        type
        updatedAt
      }
      partnerId
      productType {
        createdAt
        deletedAt
        id
        isActive
        name
        type
        updatedAt
      }
      productUnit {
        createdAt
        deletedAt
        id
        isActive
        name
        type
        updatedAt
      }
      quantity
      reviewSummary {
        percent
        starAverage
        total
      }
      serialNumber
      star
      starInfo {
        star
        total
      }
      type
      unitPrice
      updatedAt
      vehicleRegistrationPlate
      vinNumber
      yearOfManufacture
    }
    startDate
    unit
    updatedAt
    usedCount
    value
  }
}
