query partnerGetStore($id: String!) {
  partnerGetStore(id: $id) {
    address
    avatar {
      createdAt
      fileSize
      fullOriginalUrl
      fullThumbUrl
      id
      isDeleted
      mimeType
      name
      originalUrl
      ownerId
      thumbUrl
      type
      updatedAt
      videoUrl
    }
    avatarId
    createdAt
    deletedAt
    description
    email
    id
    name
    partnerId
    phoneNumber
    updatedAt
  }
}
