query quotationPriceList($id: String!) {
  quotationPriceList(id: $id) {
    accessoriesName
    createdAt
    deletedAt
    diagnosticCode
    expense
    fixable
    id
    isActive
    updatedAt
    vehicleType
    workingCode
    workingHour
  }
}
