query userGetGuide($id: String!) {
  userGetGuide(id: $id) {
    createdAt
    deletedAt
    description
    id
    instructions {
      createdAt
      deletedAt
      description
      guide {
        createdAt
        deletedAt
        description
        id
        isActive
        name
        updatedAt
      }
      guideId
      id
      isActive
      name
      updatedAt
    }
    isActive
    name
    updatedAt
  }
}
